############################
##### Overall workflow #####
############################

# Type of input data (either 'Single' or 'Cohort')
DATA: "Single"

# Should the pipeline be GPU accelerated where possible? (either 'Yes' or 'No')
GPU_ACCELERATED: "No"

# File paths to the reference genome (.fasta) and it's associated dictionary file (.dict)
REFGENOME: "/store/lkemp/publicData/b37/human_g1k_v37_decoy.fasta"
DICT: "/store/lkemp/publicData/b37/human_g1k_v37_decoy.dict"

# File path to dbSNP database
dbSNP: "/store/lkemp/publicData/b37/dbsnp_138.b37.vcf"

# Temporary file directory
TEMPDIR: "/store/lkemp/tmp/"

# Whole exome sequence settings (leave blank if analysing other data such as whole genome sequence data)
WES:
  # File path to the exome capture regions over which to operate (prefix with the '-L' flag)
  INTERVALS: ""
  # Padding (in bp) to add to each region (prefix with the '-ip' flag)
  PADDING: ""

############################
######### Trimming #########
############################

# Whether or not to trim the raw fastq reads (either 'Yes' or 'No')
TRIM: "Yes"

# If trimming, choose the adapter sequence to be trimmed (eg. `--illumina`, `--nextera` or `--small_rna`)
TRIMMING:
  ADAPTERS: "--illumina"

##############################
##### Base recalibration #####
##############################

# Resources to used for base recalibration (prefix each resource with the '--known-sites' flag if not gpu accelerated and the '--knownSites' if gpu accelerated)
RECALIBRATION:
  RESOURCES: "--known-sites /store/lkemp/publicData/b37/dbsnp_138.b37.vcf
            --known-sites /store/lkemp/publicData/b37/Mills_and_1000G_gold_standard.indels.b37.vcf
            --known-sites /store/lkemp/publicData/b37/1000G_phase1.indels.b37.vcf"